docs: improve contributing guide
aws-powertools/powertools-lambda-java pull request #1334
Opened 2023-08-02 12:47 UTC by jeromevdl

**Issue #, if available:** #1295 

## Description of changes:

Improve the contributing guide with further content, especially checkstyle for code style.

**Checklist**

 

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda-java/#tenets)
* [ ] Update tests
* [x] Update docs
* [x] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-02 13:28 UTC, scottgerring commented on CONTRIBUTING.md
> +3. You check existing open, and recently merged pull requests to make sure someone else hasn't addressed the problem already.
```suggestion
3. You've check existing open, and recently merged pull requests to make sure someone else hasn't addressed the problem already.
```

2023-08-02 13:38 UTC, kozub requested changes

2023-08-02 13:38 UTC, kozub commented on CONTRIBUTING.md
> +We recommend using [IntelliJ IDEA](https://www.jetbrains.com/idea/) from Jetbrains.
The correct name of the company is `JetBrains` ;-)

2023-08-02 13:38 UTC, kozub commented on CONTRIBUTING.md
> +        - [API reference documentation](#api-reference-documentation)
Looks that we don't have `API reference doc` section so it can be removed from this content list.

2023-08-02 13:39 UTC, scottgerring commented on CONTRIBUTING.md
> +**NOTE**: Unit tests are mandatory. End-to-end tests should be created for new modules.
Something here about test pyramid? Otherwise we'll end up with a test cube, or something 😢

2023-08-02 13:41 UTC, scottgerring commented on CONTRIBUTING.md
>  ## Contributing via Pull Requests
This section appears twice

2023-08-02 13:41 UTC, scottgerring commented on CONTRIBUTING.md
>  ## Contributing via Pull Requests
In fact everything from here down is duplicated

2023-08-02 14:38 UTC, eldimi commented on CONTRIBUTING.md
> +All the java files should contain the licence/copyright header. You can copy past it from the [license-header](license-header) file.
```suggestion
All the java files should contain the licence/copyright header. You can copy paste it from the [license-header](license-header) file.
```

2023-08-03 05:54 UTC, scottgerring approved these changes
LGTM!

2023-08-03 06:56 UTC, merged